name: Deploy

on:
  workflow_dispatch:
    inputs:
      action_type:
        description: 'Apply or destroy'
        required: true
        default: 'apply'
        type: choice
        options:
          - 'apply'
          - 'destroy'

env: 
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      WORKING_DIR: ./weekly_assignments/week_40/website

      # Resource group
      rg_website_name: rg-week_39-static-website
      rg_website_location: westeurope
      # Storage account
      sa_website_name: saweb
      source_content: <h1>Web page created with Terraform </h1>
      # Tags
      company_name: week-39_company
      billing_code: 123456789

jobs:
  terraform:
    runs-on: ubuntu-latest

    name: 'Build and Deploy Azure Resources'
    

    steps:
      - uses: actions/checkout@v4
      
      - name: Terraform init
        id: init
        working-directory: ${{ env.WORKING_DIR }}
        run: terraform init

      - name: Terraform plan
        id: plan
        working-directory: ${{ env.WORKING_DIR }}
        run: terraform plan 

      - name: Check last commit message
        id: commit
        run: echo "::set-output name=commit_message::$(git log -1 --format=%B -n 1)"

      - name: Conditionally run Terraform action
        working-directory: ${{ env.WORKING_DIR }}
        if: github.event.inputs.action_type != 'apply' && github.event.inputs.action_type != 'destroy'
        run: |
          if [[ "${{ steps.commit.outputs.message }}" == *"destroy"* ]]; then
            echo "Destroying resources"
            terraform destroy -auto-approve 
          else
            echo "Applying resources"
            terraform apply -auto-approve -var 'rg_website_name=${{ env.rg_website_name }}' -var 'rg_website_location=${{ env.rg_website_location }}' -var 'sa_website_name=${{ env.sa_website_name }}' -var 'source_content=${{ env.source_content }}' -var 'company_name=${{ env.company_name }}' -var 'billing_code=${{ env.billing_code }}'
          fi

      - name: Terraform apply
        if: github.event.inputs.action_type == 'apply'
        id: apply
        working-directory: ${{ env.WORKING_DIR }}
        run: terraform apply -auto-approve
        
      - name: Terraform destroy
        if: github.event.inputs.action_type == 'destroy'
        id: destroy
        working-directory: ${{ env.WORKING_DIR }}
        run: terraform destroy -auto-approve
        
      

