name: Dev Stage Prod for Website

on:
  push:
    paths:
      - 'weekly_assignments/week_40/website/**'

env: 
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      WORKING_DIR: ./weekly_assignments/week_40/website

      ALL_VARS: -var 'rg_website_name=rg-week_39-static-website' -var 'rg_website_location=westeurope' -var 'sa_website_name=saweb' -var 'source_content=<h1>Web page created with Terraform </h1>' -var 'company_name=week-39_company' -var 'billing_code=123456789'

jobs:
  dev_stage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Terraform init
        working-directory: ${{ env.WORKING_DIR }}
        run: terraform init

      - name: Terraform workspace select or create dev
        working-directory: ${{ env.WORKING_DIR }}
        run: terraform workspace select dev || terraform workspace new dev

      - name: Check last commit message
        id: commit
        run: echo "::set-output name=message::$(git log -1 --format=%B -n 1)"

      - name: Conditionally run Terraform action
        id: terraformAction
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          if [[ "${{ steps.commit.outputs.message }}" == *"destroy"* ]]; then
            echo "{action}={destroy}" >> $GITHUB_OUTPUT
            terraform destroy -auto-approve ${{ env.ALL_VARS }}
          else
            echo "{action}={apply}" >> $GITHUB_OUTPUT
            terraform apply -auto-approve ${{ env.ALL_VARS }}
          fi

      - name: Test dev
        working-directory: ${{ env.WORKING_DIR }}
        if: steps.terraformAction.outputs.action == 'apply'
        run: |
          curl $(terraform output -raw primary_web_endpoint)
    
  stage_prod:
    needs: dev_stage
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Terraform init
        working-directory: ${{ env.WORKING_DIR }}
        run: terraform init

      - name: Terraform workspace select or create stage
        working-directory: ${{ env.WORKING_DIR }}
        run: terraform workspace select stage || terraform workspace new stage

      - name: Check last commit message
        id: commit
        run: echo "::set-output name=message::$(git log -1 --format=%B -n 1)"

      - name: Conditionally run Terraform action
        id: terraformAction
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          if [[ "${{ steps.commit.outputs.message }}" == *"destroy"* ]]; then
            echo "{action}={destroy}" >> $GITHUB_OUTPUT
            terraform destroy -auto-approve ${{ env.ALL_VARS }}
          else
            echo "{action}={apply}" >> $GITHUB_OUTPUT
            terraform apply -auto-approve ${{ env.ALL_VARS }}
          fi

      - name: Test stage
        working-directory: ${{ env.WORKING_DIR }}
        if: steps.terraformAction.outputs.action == 'apply'
        run: |
          curl $(terraform output -raw primary_web_endpoint)
  
  prod:
    needs: stage_prod
    runs-on: ubuntu-latest
    environment:
      name: production
      url: ${{ steps.get_web_endpoint.outputs.WEB_ENDPOINT }}
    
    steps:
      - uses: actions/checkout@v4

      - name: Terraform init
        working-directory: ${{ env.WORKING_DIR }}
        run: terraform init
      
      - name: Terraform workspace select or create prod
        working-directory: ${{ env.WORKING_DIR }}
        run: terraform workspace select prod || terraform workspace new prod
      
      - name: Check last commit message
        id: commit
        run: echo "::set-output name=message::$(git log -1 --format=%B -n 1)"

      - name: Conditionally run Terraform action
        id: terraformAction
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          if [[ "${{ steps.commit.outputs.message }}" == *"destroy"* ]]; then
            echo "{action}={destroy}" >> $GITHUB_OUTPUT
            terraform destroy -auto-approve ${{ env.ALL_VARS }}
          else
            echo "{action}={apply}" >> $GITHUB_OUTPUT
            terraform apply -auto-approve ${{ env.ALL_VARS }}
          fi

      - name: Test prod
        working-directory: ${{ env.WORKING_DIR }}
        if: steps.terraformAction.outputs.action == 'apply'
        run: |
          curl $(terraform output -raw primary_web_endpoint)
      
      - name: Get Web Endpoint
        if: steps.terraformAction.outputs.action == 'apply'
        id: get_web_endpoint
        run: echo "WEB_ENDPOINT=$(terraform output -raw primary_web_endpoint)" 
        working-directory: ${{ env.WORKING_DIR }}

    
        
      



