name: Test and Validate Terraform Configuration

on:
  push:
    branches-ignore:
        - main
    paths:
        - 'terraform/**'

env: 
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      WORKING_DIR: ./terraform/

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Terraform init
        id: init
        working-directory: ${{ env.WORKING_DIR }}
        run: terraform init

      - name: Terraform Format
        run: terraform fmt -check
        working-directory: ${{ env.WORKING_DIR }}
        
      - name: Terraform Validate
        run: terraform init -backend=false && terraform validate
        working-directory: ${{ env.WORKING_DIR }}

      - name: tflint
        uses: "infinite-automations/tflint-all-in-one@v1.0.0"
        with:
          directory: "./weekly_assignments/week_42/website"
                    
      - name: tfsec 
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          soft_fail: false
      
     



      

