name: Test and Validate Terraform Configuration

on:
  push:
    branches-ignore:
        - main
    paths:
        - 'weekly_assignments/week_42/**'

env: 
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      WORKING_DIR: ./weekly_assignments/week_42/website
      ALL_VARS: 
        -var 'rg_website_name=rg-week_39-static-website' 
        -var 'rg_website_location=westeurope' 
        -var 'sa_website_name=saweb 
        -var 'source_content=<h1>Web page created with Terraform </h1>' 
        -var 'company_name=week-39_company' 
        -var 'billing_code=1234567890' 

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Terraform init
        id: init
        working-directory: ${{ env.WORKING_DIR }}
        run: terraform init

      - name: Terraform Format
        run: terraform fmt -check
        working-directory: ${{ env.WORKING_DIR }}
        
      - name: Terraform Validate
        run: terraform init -backend=false && terraform validate
        working-directory: ${{ env.WORKING_DIR }}

      

